### ISSUE TITLE
Select the authentication service at the connection

### ISSUE THREAD

**Issue by damienld22** [zetapush/zetapush-angular#3]
Hello,

There isn't the possibility of choosing the authentication service when we use `ZetaPushConnection`. 
Can you add it ? 

Here is my code for the connection :

    this.zpConnection.connect({'login':'user', 'password': 'password'}).then(() => {
        console.debug("ZetaPushConnection:OK");
    });

Damien

**Comment by ghoullier** [comment]
closed by https://github.com/zetapush/zetapush-js/pull/9
